# Generated by Django 5.0.3 on 2024-06-15 09:43

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_task_time_created_alter_task_time_to_alert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='invite_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True, verbose_name='Invite Code'),
        ),
    ]
