# Generated by Django 5.0.3 on 2024-06-19 15:30

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_task_time_created_alter_workspace_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_workspace', to='api.workspace'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='invite_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True, verbose_name='Invite Code'),
        ),
    ]
