# Generated by Django 5.0.3 on 2024-06-19 15:37

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_comment_workspace_alter_workspace_invite_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Workspace',
            new_name='workspace',
        ),
        migrations.AlterField(
            model_name='workspace',
            name='invite_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True, verbose_name='Invite Code'),
        ),
    ]
