# Generated by Django 5.0.3 on 2024-06-19 20:14

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_workspace_comment_workspace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='workspace',
        ),
        migrations.AlterField(
            model_name='workspace',
            name='invite_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True, verbose_name='Invite Code'),
        ),
    ]
